[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Shig enables distributed live streams via the Ferdivers"
license = "AGPL-3.0"
homepage = "https://shig.de/"
documentation = "https://github.com/shide/shig/doc/undex.md"
repository = "https://github.com/shide/shig"

[package]
name = "shig_server"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
publish = false

[dependencies]
actix-web = { version = "4", features = ["openssl"] }
openssl = { version = "0.10" }
clap = { version = "4.5.21", features = ["derive"] }
config = "0.14.0"
