CREATE TABLE friend_roles
(
    id   INTEGER     NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(40) NOT NULL
);

INSERT INTO "friend_roles" ("id", "name")
VALUES (1, 'guest');
INSERT INTO "friend_roles" ("id", "name")
VALUES (2, 'moderator');
INSERT INTO "friend_roles" ("id", "name")
VALUES (3, 'host');
INSERT INTO "friend_roles" ("id", "name")
VALUES (4, 'admin');
INSERT INTO "friend_roles" ("id", "name")
VALUES (5, 'bot');
