[server]
port = 8080
host = '127.0.0.1'

[server.tls]
enabled = true
cert = "config/certs/cert.pem"
key = "config/certs/key.pem"

[federation]
enable = true
domain = "localhost:8080"
instance = "shig"
token = "this-token-must-be-changed-in-public"
tls = true

[database]
connection = "postgres://postgres@localhost:5432/shig"
pool_size = 30

[jwt]
auth_token_key = "session-auth-token-key"
refresh_token_key = "refresh-token-key-long-long"
session_live_time = 86400 # 1day

[mail]
enable = false
smtp_user = "from@gmail.com"
smtp_pass = ""
smtp_host = "smtp.gmail.com"
smtp_port = 587
