[server]
port = 8080
host = '127.0.0.1'

[server.tls]
enabled = false
cert = "config/certs/cert.pem"
key = "config/certs/key.pem"

[federation]
enable = true
domain = "localhost"
instance = "shig"
token = "this-token-must-be-changed-in-public"
tls = true

[database]
name = "database.db"

[jwt]
key = "session-auth-token-key"
live_time = 120
